SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET AUTOCOMMIT = 0;
START TRANSACTION;
SET time_zone = "+00:00";

CREATE TABLE JUGADORES (
  IDJ int(11) NOT NULL PRIMARY KEY,
  Nombre varchar(26) NOT NULL UNIQUE,
  Pass varchar(20) NOT NULL,
  Sexo char(1) NOT NULL,
  Puntos int(11) NOT NULL DEFAULT 0,
  Posicion int(11) NOT NULL DEFAULT 0,
  Avatar varchar(27) NOT NULL DEFAULT 'no_user.png',
  Aciertos int(11) NOT NULL DEFAULT 0,
  Fallos int(11) NOT NULL DEFAULT 0,
  onnline int(1) NOT NULL DEFAULT 0,
  Idioma int(1) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE PALABRAS(
  IDP int(11) NOT NULL,
  IDL int(1) NOT NULL,
  Num_letras int(11) NOT NULL,
  Tilde int(1) DEFAULT 0,
  Aciertos int(11) NOT NULL DEFAULT 0,
  Fallos int(11) NOT NULL DEFAULT 0,
  PRIMARY KEY (IDP,IDL)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE ACIERTOS (
  IDJ int(11) NOT NULL DEFAULT 0,
  IDP int(11) NOT NULL DEFAULT 0,
  IDL int(11) NOT NULL DEFAULT 0,
  Aciertos int(11) NOT NULL DEFAULT 0,
  Fallos int(11) NOT NULL DEFAULT 0,
  Vidas int(11) NOT NULL DEFAULT 0,
  Orden int(11) NOT NULL UNIQUE,
  PRIMARY KEY (IDJ,IDP,IDL),
  FOREIGN KEY (IDJ) REFERENCES JUGADORES(IDJ) ON DELETE CASCADE,
  FOREIGN KEY (IDP,IDL) REFERENCES PALABRAS(IDP,IDL) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
 
CREATE TABLE SPANISH(
IDS int(11) NOT NULL PRIMARY KEY,
Palabra varchar(25) NOT NULL UNIQUE
) ENGINE=InnoDB DEFAULT CHARSET=utf8;  
  
CREATE TABLE ANGLICISMOS(
IDA int(11) NOT NULL PRIMARY KEY,
Palabra varchar(25) NOT NULL UNIQUE
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE INGLES(
IDI int(11) NOT NULL PRIMARY KEY,
Palabra varchar(25) NOT NULL UNIQUE
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE FRANCES(
IDF int(11) NOT NULL PRIMARY KEY,
Palabra varchar(25) NOT NULL UNIQUE
) ENGINE=InnoDB DEFAULT CHARSET=utf8;  

COMMIT;